name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      # App/test env vars
      NEXT_PUBLIC_APP_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
      SUPABASE_SERVICE_ROLE_KEY: test-service-key
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: test-maps
      NEXT_PUBLIC_SANITY_PROJECT_ID: test-project
      NEXT_PUBLIC_SANITY_DATASET: production
      PESAPAL_API_BASE_URL: https://pesapal.test
      PESAPAL_CONSUMER_KEY: test-key
      PESAPAL_CONSUMER_SECRET: test-secret
      PESAPAL_IPN_IDS: ipn-123
      WHATSAPP_API_VERSION: v20.0
      WHATSAPP_PHONE_NUMBER_ID: 1234567890
      WHATSAPP_ACCESS_TOKEN: test-wa-token
      NEXT_PUBLIC_SHOPKEEPER_WA_NUMBER: +256700000000
      SMTP_USER: ci@example.com
      SMTP_PASSWORD: test
      RECIPIENT_ADDRESS: ops@example.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit/integration tests (Vitest)
        run: npm run test -- --reporter=default

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests (Playwright)
        run: npm run e2e

